### ISSUE TITLE
Uncaught type error

### ISSUE THREAD

**Issue by Fresheyeball** [chaika2013/ide-haskell#29]
```
Uncaught TypeError: Cannot read property 'start' of null
/usr/share/atom/resources/app/src/workspace.js:614
Hide Stack Trace
TypeError: Cannot read property 'start' of null
  at CompletionDatabase._update (/home/isaac/.atom/packages/ide-haskell/lib/completion-db.coffee:35:38)
  at CompletionDatabase.update (/home/isaac/.atom/packages/ide-haskell/lib/completion-db.coffee:29:6)
  at CompleteProvider.buildCompletionList (/home/isaac/.atom/packages/ide-haskell/lib/complete-provider.coffee:296:18)
  at CompleteProvider.buildCompletionList (/home/isaac/.atom/packages/ide-haskell/lib/complete-provider.coffee:1:1)
  at CompleteProvider.onSaved (/home/isaac/.atom/packages/ide-haskell/lib/complete-provider.coffee:97:6)
  at /home/isaac/.atom/packages/ide-haskell/lib/complete-provider.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:973:19)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:585:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app/src/pane.js:511:16)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app/src/pane.js:501:19)
  at Workspace.module.exports.Workspace.saveActivePaneItemAndReportErrors (/usr/share/atom/resources/app/src/workspace.js:603:44)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app/src/workspace.js:593:19)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:167:20)
```

**Comment by jmquigs** [comment]
One possibility is that the save callbacks that are set up by the completion provider are left enabled after the package is deactivated.  Deactivation nulls out the pendingProcessController, so a save hook would trigger this error.  But so far I haven't been able to repro that scenario, or any other.

**Comment by lierdakil** [comment]
Strange indeed. I'm tempted to just add a dumb check for `pendingProcessController` and call `createPendingProcessController` if it's null...

**Comment by lierdakil** [comment]
Please report if this or similar issue persists after 0.3.3
