### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of null

### ISSUE THREAD

**Issue by aceLren** [chaika2013/ide-haskell#36]
I got the atom update and the ide-haskell about the same time so I'm not sure what did it, but any time I save now I get the Uncaught TypeError: Cannot read property 'start' of null.  The generated error is below.  It looks like @manager.pendingProcessController is null?  If atom has it somewhere else now I'm not sure where it would be.  Anyway:

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [ide-haskell](https://github.com/chaika2013/ide-haskell) package, v0.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:782

TypeError: Cannot read property 'start' of null
  at CompletionDatabase._update (/Users/asaelh/.atom/packages/ide-haskell/lib/completion-db.coffee:35:38)
  at CompletionDatabase.update (/Users/asaelh/.atom/packages/ide-haskell/lib/completion-db.coffee:29:6)
  at CompleteProvider.buildCompletionList (/Users/asaelh/.atom/packages/ide-haskell/lib/complete-provider.coffee:292:5)
  at CompleteProvider.buildCompletionList (/Users/asaelh/.atom/packages/ide-haskell/lib/complete-provider.coffee:1:1)
  at CompleteProvider.onSaved (/Users/asaelh/.atom/packages/ide-haskell/lib/complete-provider.coffee:140:19)
  at /Users/asaelh/.atom/packages/ide-haskell/lib/complete-provider.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:172:20)

```

### Commands

```
  2x -2:54.2 core:save (atom-text-editor.editor.vim-mode.command-mode)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "ide-haskell": {
    "ghcModPath": "/Users/asaelh/Dev/HTools/.cabal-sandbox/bin/ghc-mod",
    "stylishHaskellPath": "/Users/asaelh/Dev/HTools/.cabal-sandbox/bin/stylish-haskell"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
file-icons, v1.4.10
ide-haskell, v0.3.1
javascript-snippets, v1.0.0
language-haskell, v1.0.0
language-jade, v0.3.0
linter, v0.11.1
monokai, v0.12.0
tabs-to-spaces, v0.8.1
tasks, v1.2.4
vim-mode, v0.31.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
This looks like something @jmquigs could offer some insight into. I can't reproduce it and don't see why this could happen in the first place.

**Comment by jmquigs** [comment]
@lierdakil, I will try to repro.  There might be some scenario where the pendingProcessController is nulled out but the package is still active.

**Comment by aceLren** [comment]
Thanks for looking at this so quickly!  After both of you said you couldn't reproduce it I decided to just uninstall / reinstall - I did and that seemed to have worked.  Not sure what happened.

**Comment by lierdakil** [comment]
Looks like we had similar report before 0.3.1, i.e. #29. I think this requires some investigation.
