### ISSUE TITLE
Failed to activate the ide-haskell package

### ISSUE THREAD

**Issue by rchipman** [chaika2013/ide-haskell#47]
Just try to load a cabal created haskel project.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [ide-haskell](https://github.com/chaika2013/ide-haskell) package, v0.3.5

### Stack Trace

Failed to activate the ide-haskell package

```
At spawn EACCES

Error: spawn EACCES
    at exports._errnoException (util.js:753:11)
    at ChildProcess.spawn (child_process.js:1160:11)
    at Object.exports.spawn (child_process.js:993:9)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
    at run (/Users/rchipman/.atom/packages/ide-haskell/lib/util-ghc-mod.coffee:24:12)
    at Object.flag (/Users/rchipman/.atom/packages/ide-haskell/lib/util-ghc-mod.coffee:226:12)
    at PendingBackend.processPendingTask (/Users/rchipman/.atom/packages/ide-haskell/lib/pending-backend.coffee:61:39)
    at PendingBackend.start (/Users/rchipman/.atom/packages/ide-haskell/lib/pending-backend.coffee:27:19)
    at MainCompletionDatabase.rebuild (/Users/rchipman/.atom/packages/ide-haskell/lib/completion-db.coffee:101:45)
    at new MainCompletionDatabase (/Users/rchipman/.atom/packages/ide-haskell/lib/completion-db.coffee:83:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "ide-haskell": {
    "ghcModPath": "/Users/rchipman/Library/Haskell/bin",
    "stylishHaskellPath": "/Users/rchipman/Library/Haskell/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.2
ide-haskell, v0.3.5
language-haskell, v1.0.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Do you have ghc-mod installed? Are you able to run it? `spawn EACCES` basically means that Atom couldn't run ghc-mod due to incorrect permissions...

**Comment by rchipman** [comment]
Yes i have ghc-mod installed and can run ghci

**Comment by lierdakil** [comment]
Um. What does ghci have to do with anything?

**Comment by rchipman** [comment]
![screen shot 2015-03-12 at 4 48 54 pm](https://cloud.githubusercontent.com/assets/3871032/6627879/b08b50e2-c8d7-11e4-8d5b-9187d65a4a58.png)
I dunno, new to haskell, I though ghc-mod installed ghci but I could be wrong.

**Comment by rchipman** [comment]
Hmm.. i think i fixed it, I had to put the fully qualified path to ghc-mod and stylish-haskell in the settings. Sorry for confusion.
